### ISSUE TITLE
The number of image in 'ETH-Pedcross2' is 837?

### ISSUE THREAD

**Issue by weiweikong** [yuxng/L2A#1]
Hi,
 in file `global.m`, https://github.com/yuxng/MDP_Tracking/blob/master/globals.m#l27, the number of image in 'ETH-Pedcross2' is 840, which is not match the number in 2DMOT2015 package(837). Is that right?

**Comment by yuxng** [comment]
Hello,

In the version I downloaded, ETH-Pedcross2 has 840 images, but the annotations are just for frame 1 to frame 837. I guess the authors of the MOT dataset have deleted frame 838 ~ 840. Feel free to change the number in global.m
