### ISSUE TITLE
The function 'convertTXTStruct' corresponding to the input parameter of type 'char' is not defined

### ISSUE THREAD

**Issue by YuanTai** [yuxng/L2A#10]
i ran the MOT_cross_validation.m. and it ran a period of time says "The function 'convertTXTStruct' corresponding to the input parameter of type 'char' is not defined" in evaluateTracking.m.  i search on the internet for a long time,but never get a solution.

**Comment by yuxng** [comment]
This function is included in the devkit of the MOT 2015 dataset.
