### ISSUE TITLE
bug in MOT_initialize.m？

### ISSUE THREAD

**Issue by PencilAndBike** [yuxng/L2A#3]
When I ran MOT_test.m it met a problem

```
Error using svmtrain (line 233)
Y must be a vector or a character array.

Error in MDP_initialize (line 28)
tracker.w_active = svmtrain(tracker.lactive, tracker.factive, '-c 1 -q');

Error in MDP_train (line 49)
    tracker = MDP_initialize(I, dres_det, labels, opt);

Error in MOT_cross_validation (line 39)
            tracker = MDP_train(idx_train{j}, tracker);
```

It seems that on line 28 in MDP_initialize.m:

> tracker.w_active = svmtrain(tracker.lactive, tracker.factive, '-c 1 -q');

should be:

> tracker.w_active = svmtrain( tracker.factive, tracker.lactive, '-c 1 -q');

because the orders of features and labels are inverse.

I change their orders but another problem happened.

```
Error using internal.stats.parseArgs (line 42)
Wrong number of arguments.

Error in svmtrain (line 291)
[kfun,optimMethod, plotflag, polyOrder, mlpParams, boxC,  rbf_sigma, ...

Error in MDP_initialize (line 29)
tracker.w_active = svmtrain(tracker.factive,tracker.lactive, '-c 1 -q');

Error in MDP_train (line 49)
    tracker = MDP_initialize(I, dres_det, labels, opt);

Error in MOT_test (line 39)
            tracker = MDP_train(idx_train{j}, tracker);
```

It seems due to the last parameter '-c 1 -q' of 

> tracker.w_active = svmtrain(tracker.factive,tracker.lactive, '-c 1 -q');

is wrong.

Is it true? And how to fix it?

**Comment by yuxng** [comment]
Please make sure you are using the libsvm in the 3rd party in this repo

**Comment by PencilAndBike** [comment]
Thanks a lot for your help. It works.
