### ISSUE TITLE
Cannot find an exact (case-sensitive) match for 'lk'

### ISSUE THREAD

**Issue by KhalidYousif** [yuxng/L2A#5]
Hello,

I have followed all the instructions and when I run MOT_test.m, I get the following error:

```
MOT_test
Training on sequence: TUD-Stadtmitte
load images from file results/TUD-Stadtmitte_dres_image.mat done
TUD-Stadtmitte: 10 positive sequences
initialize tracker from scratch
.Cannot find an exact (case-sensitive) match for 'lk'

The closest match is: LK in D:\MDP_Tracking-master\LK.m


Error in LK (line 23)
xFJ = lk(2, I, J, xFI, xFII, level);

Error in LK_tracking (line 37)
    [BB2, xFJ, flag, medFB, medNCC, medFB_left, medFB_right, medFB_up, medFB_down] = LK(I_crop, J_crop, ...

Error in MDP_feature_tracked (line 12)
tracker = LK_tracking(frame_id, dres_image, dres_det, tracker);

Error in MDP_value (line 14)
    [tracker, f] = MDP_feature_tracked(frame_id, dres_image, dres_det, tracker);

Error in MDP_train (line 185)
            tracker = MDP_value(tracker, fr, dres_image, dres, []);

Error in MOT_test (line 39)
            tracker = MDP_train(idx_train{j}, tracker);
```

Any ideas what the problem is?

Thanks,
Khalid

**Comment by yuxng** [comment]
Have you compiled the code by running compile.m?

**Comment by KhalidYousif** [comment]
Thanks for your reply, yes I have:

```
Building with 'Microsoft Visual C++ 2015 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2015 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2015 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2015 Professional'.
MEX completed successfully.
Compilation finished.
```

Also note that I am running it on Windows.

**Comment by yuxng** [comment]
Then you should have the lk.cpp file compiled to an executable to resolve the error "Cannot find an exact (case-sensitive) match for 'lk'"

**Comment by KhalidYousif** [comment]
After compiling, I have a MEXW64 File generated, is that the executable that you mentioned? I am still getting the same error after the compilation. I want to note that I did 1 change to the compile.m to get it to compile:

The following:

`eval(['mex D:/MDP_Tracking-master/MDP_Tracking-master/lk.cpp -O' include lib]);`

Was changed to:

`eval(['mex D:/MDP_Tracking-master/MDP_Tracking-master/lk.cpp -output' include lib]);`

If I don't do this change, I get a mex error. Although I do not think this is the issue.

**Comment by yuxng** [comment]
Yes, that is the executable I mean. But I am not sure why you can not call the compiled mex function in this case.

**Comment by KhalidYousif** [comment]
Where should this executable be located? I currently have it with the rest of the source files in  

`D:/MDP_Tracking-master/MDP_Tracking-master/`

Is there any place specifically it needs to be? Also, does it need to have a specific name? currently, the generated name is `..MEXW64`.

**Comment by yuxng** [comment]
The files will be generated under the same directory of the .cpp files. Your path is correct. The "mexw64" is the default name in Windows of mex executable file. No specific name is needed. In my case, I have "lk.mexa64" with Ubuntu.

**Comment by KhalidYousif** [comment]
Thanks for the info, I renamed it to `lk.mexa64` and now I get the following error:

```
.Invalid MEX-file 'D:\MDP_Tracking-master2\MDP_Tracking-master\lk.mexw64': The specified module could not be found.

Error in LK (line 23)
xFJ = lk(2, I, J, xFI, xFII, level);

Error in LK_tracking (line 37)
    [BB2, xFJ, flag, medFB, medNCC, medFB_left, medFB_right, medFB_up, medFB_down] = LK(I_crop, J_crop, ...

Error in MDP_feature_tracked (line 12)
tracker = LK_tracking(frame_id, dres_image, dres_det, tracker);

Error in MDP_value (line 14)
    [tracker, f] = MDP_feature_tracked(frame_id, dres_image, dres_det, tracker);

Error in MDP_train (line 185)
            tracker = MDP_value(tracker, fr, dres_image, dres, []);

Error in MOT_test (line 39)
            tracker = MDP_train(idx_train{j}, tracker);
```

**Comment by yuxng** [comment]
You should not rename it. Please check if there is something wrong with your mex. This is out of scope of the code. Close the issue.

**Comment by KhalidYousif** [comment]
The issue was resolved by copying the opencv .dll files into the same folder.

regards.
Khalid
