### ISSUE TITLE
Running code without building dres structure

### ISSUE THREAD

**Issue by shivakumardistproc** [yuxng/L2A#6]
Dear Yu Xiang,
Building dres structure takes huge hard disk space  and time. 
Is it possible to run code with out building dres structure? Can we read one frame at a time (like "On-line" processing)?

Thanking you
Shiva

**Comment by yuxng** [comment]
Hello,

I think it is possible. The dres structure can save time in training. Otherwise, we have to read the images again and again during training. For testing, since we only process one image once, it is possible to not use the dres structure.
